### ISSUE TITLE
Question XPath

### ISSUE THREAD

**Issue by mattlev2** [gabays/Cours_COSME_2019#12]
J'ai un problème pour expliquer les fonctions xpath qui prennent des noeuds ou des chaînes de caractères comme argument: 

``concat(arg1, arg2)``

a) Si arg1 et/ou arg2 sont des noeuds ou des expressions XPath, on a une traduction automatique en chaîne de caractères: si j'ai bien compris, pour noeud1, arg1=noeud1/text(). 

b) Si ce n'est pas le cas, il faut l'indiquer par des guillemets simples: arg1 et arg2 sont des chaînes de caractères. Mais dans la syntaxe, c'est considéré comme des chaînes de caractère à la base, du coup j'ai du mal à comprendre.

Est-ce que c'est vraiment ça (je n'ai pas encore trouvé une section qui aborde ça dans la documentation), et comment on explique ça ?

**Comment by ArianePinche** [comment]
la fonction concat "colle" deux chaines de caractères ensemble, tu peux le traduire aisément : 
- concat('chaineCaracteres1', 'chaineCaracteres2')
Enfin, en Xpath quand tu sélectionnes un élément par exemple @type, tu sélectionnes par défaut sa valeur, soit la chaine de caractères qu'il contient (quand tu as du mal à expliquer, donne des exemples): 
<div type='act' n='1'>
- concat(@type, ' ', @n) =>  act 1 
Je ne sais pas si c'est clair, mais j'espère que cela pourra t'aider.

**Comment by mattlev2** [comment]
Ok merci !
> Enfin, en Xpath quand tu sélectionnes un élément par exemple @type, tu sélectionnes par défaut sa valeur, soit la chaine de caractères qu'il contient

C'était ça qui me manquait.  Je vais ajouter un exemple comme le tien, c'est effectivement le plus simple.
