### ISSUE TITLE
Problème dans la numérotation des vers

### ISSUE THREAD

**Issue by maieul** [gabays/Cours_COSME_2019#15]
@gabays 

En préparant la version LaTeX du texte (coquin, c'est de la versification !), j'ai constaté un décalage dans les numéro de vers (inséré automatiquement par LaTeX), par rapport à la version HTML.

En regardant plus précisement le code source xml, je vois que du a des fois plusieurs fois le même numéro de vers
- vers 37: https://github.com/gabays/Cours_COSME_2019/blob/3fed3e15be03f9621c9961a2aae8289ddebfc383/Corpus/Andromaque_c.xml#L869
- vers 134 : https://github.com/gabays/Cours_COSME_2019/blob/3fed3e15be03f9621c9961a2aae8289ddebfc383/Corpus/Andromaque_c.xml#L1142

Est-ce fait exprès ? Est-ce qu'il faut que je ne compte pas ce deuxième vers 37/134 ?

**Comment by maieul** [comment]
Aussi

vers 141 https://github.com/gabays/Cours_COSME_2019/blob/3fed3e15be03f9621c9961a2aae8289ddebfc383/Corpus/Andromaque_c.xml#L1166

**Comment by gabays** [comment]
Salut Maïeul! Non, c'est normal – et encore plus coquin. C'est une antilabe: un même alexandrin est réparti sur plusieurs répliques!

**Comment by maieul** [comment]
tu choisi pas des exemples simples ;-)

**Comment by gabays** [comment]
C'est pas moi, c'est la vie qui n'est pas simple… Toi qui fais de la théologie, il y a [un bureau des réclamations en ligne ici](https://english.thekotel.org/kotel/tehillim/).
